---
version: "3"
services:
  app: # simple chat with chatgpt
    build: .
      #context: ./
      #target: PRODUCTION_STAGE
    container_name: chat-ai
    #volumes:
      #- ./:/app
      #- /app/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    restart: unless-stopped
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    #command: sh
